# Build and run tests every night on non-Docker systems.
name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:

  swipl-lint:
    name: SWI-Prolog Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install swi-prolog
        run: ./.github/install-swi-prolog.sh stable

      - name: Checkout tus
        uses: actions/checkout@v3
        with:
          repository: terminusdb/tus
          path: tus
          ref: v0.0.5

      - name: Install tus
        run: swipl -g "pack_install('file://$GITHUB_WORKSPACE/tus', [interactive(false)])"

      - name: Remove tus sources
        run: rm -rf ./tus

      - name: Download swipl-lint
        run: make download-lint

      - name: Lint
        run: make lint

  openapi_lint:
    name: OpenAPI Lint
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository      
        uses: actions/checkout@v3

      - name: Lint
        run: npx @redocly/cli lint docs/openapi.yaml
      