name: Publish Snap

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Download Snap image
        uses: actions/download-artifact@v4
        with:
          name: terminusdb-snap
          path: download_snap/

      - name: Determine exact snap path
        id: snap_path_step
        run: |
          echo "snap_path=$(find download_snap -name '*.snap')"  >> "$GITHUB_OUTPUT"

      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.snap_path_step.outputs.snap_path }}
          release: stable

