# Build Snap
name: Build Snap

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - ".github/workflows/snap-build.yml"
  
jobs:
  snap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rsync -r ./ distribution/terminusdb_source/

      - uses: snapcore/action-build@v1
        id: snapcraft
        with:
          path: distribution

      - uses: actions/upload-artifact@v4
        with:
          name: terminusdb-snap
          path: ${{ steps.snapcraft.outputs.snap }}

      - run: sudo snap install ${{ steps.snapcraft.outputs.snap }} --dangerous

      - run: |
          terminusdb store init
          terminusdb serve &
          export TERMINUSDB_EXEC_PATH=/snap/bin/terminusdb
          export TERMINUSDB_BASE_URL='http://127.0.0.1:6363'
          sleep 5 # Sleep a bit to be sure that the server started
          cd tests && npm i && npm run test
