# Build Snap
name: Snap Build

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - ".github/workflows/snap-build.yml"
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy Sources
        run: rsync -r ./ distribution/terminusdb_source/

      - name: Build
        uses: snapcore/action-build@v1
        id: snapcraft
        with:
          path: distribution

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: terminusdb-snap
          path: ${{ steps.snapcraft.outputs.snap }}
        
  test:
    name: Integration Tests
    needs: 
      - build
    runs-on: ubuntu-latest

    steps:   
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: terminusdb-snap
          path: download_snap/

      - name: Install
        run: sudo snap install download_snap/*.snap --dangerous

      - name: Test
        run: |
          terminusdb store init
          terminusdb serve &
          export TERMINUSDB_EXEC_PATH=/snap/bin/terminusdb
          export TERMINUSDB_BASE_URL='http://127.0.0.1:6363'
          sleep 5 # Sleep a bit to be sure that the server started
          cd tests && npm i && npm run test
